
/*
 * generated by Xtext
 */
package fr.onair.dsl.safety.altarica.ui.internal;

import org.apache.log4j.Logger;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class AltaricaActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static AltaricaActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("fr.onair.dsl.safety.altarica.Altarica", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("fr.onair.dsl.safety.altarica.Altarica")).with(getUiModule("fr.onair.dsl.safety.altarica.Altarica"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static AltaricaActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("fr.onair.dsl.safety.altarica.Altarica".equals(grammar)) {
		  return new fr.onair.dsl.safety.altarica.AltaricaRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("fr.onair.dsl.safety.altarica.Altarica".equals(grammar)) {
		  return new fr.onair.dsl.safety.altarica.ui.AltaricaUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
