/*
* generated by Xtext
*/
package fr.onair.dsl.safety.altarica.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AltaricaAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/onair/dsl/safety/altarica/parser/antlr/internal/InternalAltarica.tokens");
	}
}
